<?php
use App\Models\Commune;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CommunesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Commune::truncate();
        Schema::enableForeignKeyConstraints();
        Commune::insert([
            ['name'=>'Arica','province_id'=>1],
            ['name'=>'Camarones','province_id'=>1],
            ['name'=>'General Lagos','province_id'=>2],
            ['name'=>'Putre','province_id'=>2],
            ['name'=>'Alto Hospicio','province_id'=>3],
            ['name'=>'Iquique','province_id'=>3],
            ['name'=>'Camiña','province_id'=>4],
            ['name'=>'Colchane','province_id'=>4],
            ['name'=>'Huara','province_id'=>4],
            ['name'=>'Pica','province_id'=>4],
            ['name'=>'Pozo Almonte','province_id'=>4],
            ['name'=>'Tocopilla','province_id'=>5],
            ['name'=>'María Elena','province_id'=>5],
            ['name'=>'Calama','province_id'=>6],
            ['name'=>'Ollague','province_id'=>6],
            ['name'=>'San Pedro de Atacama','province_id'=>6],
            ['name'=>'Antofagasta','province_id'=>7],
            ['name'=>'Mejillones','province_id'=>7],
            ['name'=>'Sierra Gorda','province_id'=>7],
            ['name'=>'Taltal','province_id'=>7],
            ['name'=>'Chañaral','province_id'=>8],
            ['name'=>'Diego de Almagro','province_id'=>8],
            ['name'=>'Copiapó','province_id'=>9],
            ['name'=>'Caldera','province_id'=>9],
            ['name'=>'Tierra Amarilla','province_id'=>9],
            ['name'=>'Vallenar','province_id'=>10],
            ['name'=>'Alto del Carmen','province_id'=>10],
            ['name'=>'Freirina','province_id'=>10],
            ['name'=>'Huasco','province_id'=>10],
            ['name'=>'La Serena','province_id'=>11],
            ['name'=>'Coquimbo','province_id'=>11],
            ['name'=>'Andacollo','province_id'=>11],
            ['name'=>'La Higuera','province_id'=>11],
            ['name'=>'Paihuano','province_id'=>11],
            ['name'=>'Vicuña','province_id'=>11],
            ['name'=>'Ovalle','province_id'=>12],
            ['name'=>'Combarbalá','province_id'=>12],
            ['name'=>'Monte Patria','province_id'=>12],
            ['name'=>'Punitaqui','province_id'=>12],
            ['name'=>'Río Hurtado','province_id'=>12],
            ['name'=>'Illapel','province_id'=>13],
            ['name'=>'Canela','province_id'=>13],
            ['name'=>'Los Vilos','province_id'=>13],
            ['name'=>'Salamanca','province_id'=>13],
            ['name'=>'La Ligua','province_id'=>14],
            ['name'=>'Cabildo','province_id'=>14],
            ['name'=>'Zapallar','province_id'=>14],
            ['name'=>'Papudo','province_id'=>14],
            ['name'=>'Petorca','province_id'=>14],
            ['name'=>'Los Andes','province_id'=>15],
            ['name'=>'San Esteban','province_id'=>15],
            ['name'=>'Calle Larga','province_id'=>15],
            ['name'=>'Rinconada','province_id'=>15],
            ['name'=>'San Felipe','province_id'=>16],
            ['name'=>'Llaillay','province_id'=>16],
            ['name'=>'Putaendo','province_id'=>16],
            ['name'=>'Santa María','province_id'=>16],
            ['name'=>'Catemu','province_id'=>16],
            ['name'=>'Panquehue','province_id'=>16],
            ['name'=>'Quillota','province_id'=>17],
            ['name'=>'La Cruz','province_id'=>17],
            ['name'=>'La Calera','province_id'=>17],
            ['name'=>'Nogales','province_id'=>17],
            ['name'=>'Hijuelas','province_id'=>17],
            ['name'=>'Valparaíso','province_id'=>18],	
            ['name'=>'Viña del Mar','province_id'=>18],
            ['name'=>'Concón','province_id'=>18],
            ['name'=>'Quintero','province_id'=>18],
            ['name'=>'Puchuncaví','province_id'=>18],
            ['name'=>'Casablanca','province_id'=>18],
            ['name'=>'Juan Fernández','province_id'=>18],
            ['name'=>'San Antonio','province_id'=>19],
            ['name'=>'Cartagena','province_id'=>19],
            ['name'=>'El Tabo','province_id'=>19],
            ['name'=>'El Quisco','province_id'=>19],
            ['name'=>'Algarrobo','province_id'=>19],
            ['name'=>'Santo Domingo','province_id'=>19],
            ['name'=>'Isla de Pascua','province_id'=>20],
            ['name'=>'Quilpué','province_id'=>21],
            ['name'=>'Limache','province_id'=>21],
            ['name'=>'Olmué','province_id'=>21],
            ['name'=>'Villa Alemana','province_id'=>21],
            ['name'=>'Colina','province_id'=>22],
            ['name'=>'Lampa','province_id'=>22],
            ['name'=>'Tiltil','province_id'=>22],
            ['name'=>'Santiago','province_id'=>23],
            ['name'=>'Vitacura','province_id'=>23],
            ['name'=>'San Ramón','province_id'=>23],
            ['name'=>'San Miguel','province_id'=>23],
            ['name'=>'San Joaquín','province_id'=>23],
            ['name'=>'Renca','province_id'=>23],
            ['name'=>'Recoleta','province_id'=>23],
            ['name'=>'Quinta Normal','province_id'=>23],
            ['name'=>'Quilicura','province_id'=>23],
            ['name'=>'Pudahuel','province_id'=>23],
            ['name'=>'Providencia','province_id'=>23],
            ['name'=>'Peñalolén','province_id'=>23],
            ['name'=>'Pedro Aguirre Cerda','province_id'=>23],
            ['name'=>'Ñuñoa','province_id'=>23],
            ['name'=>'Maipú','province_id'=>23],
            ['name'=>'Macul','province_id'=>23],
            ['name'=>'Lo Prado','province_id'=>23],
            ['name'=>'Lo Espejo','province_id'=>23],
            ['name'=>'Lo Barnechea','province_id'=>23],
            ['name'=>'Las Condes','province_id'=>23],
            ['name'=>'La Reina','province_id'=>23],
            ['name'=>'La Pintana','province_id'=>23],
            ['name'=>'La Granja','province_id'=>23],
            ['name'=>'La Florida','province_id'=>23],
            ['name'=>'La Cisterna','province_id'=>23],
            ['name'=>'Independencia','province_id'=>23],
            ['name'=>'Huechuraba','province_id'=>23],
            ['name'=>'Estación Central','province_id'=>23],
            ['name'=>'El Bosque','province_id'=>23],
            ['name'=>'Conchalí','province_id'=>23],
            ['name'=>'Cerro Navia','province_id'=>23],
            ['name'=>'Cerrillos','province_id'=>23],
            ['name'=>'Puente Alto','province_id'=>24],
            ['name'=>'San José de Maipo','province_id'=>24],
            ['name'=>'Pirque','province_id'=>24],
            ['name'=>'San Bernardo','province_id'=>25],
            ['name'=>'Buin','province_id'=>25],
            ['name'=>'Paine','province_id'=>25],
            ['name'=>'Calera de Tango','province_id'=>25],
            ['name'=>'Melipilla','province_id'=>26],
            ['name'=>'Alhué','province_id'=>26],
            ['name'=>'Curacaví','province_id'=>26],
            ['name'=>'María Pinto','province_id'=>26],
            ['name'=>'San Pedro','province_id'=>26],
            ['name'=>'Isla de Maipo','province_id'=>27],
            ['name'=>'El Monte','province_id'=>27],
            ['name'=>'Padre Hurtado','province_id'=>27],
            ['name'=>'Peñaflor','province_id'=>27],
            ['name'=>'Talagante','province_id'=>27],
            ['name'=>'Codegua','province_id'=>28],
            ['name'=>'Coínco','province_id'=>28],
            ['name'=>'Coltauco','province_id'=>28],
            ['name'=>'Doñihue','province_id'=>28],
            ['name'=>'Graneros','province_id'=>28],
            ['name'=>'Las Cabras','province_id'=>28],
            ['name'=>'Machalí','province_id'=>28],
            ['name'=>'Malloa','province_id'=>28],
            ['name'=>'Mostazal','province_id'=>28],
            ['name'=>'Olivar','province_id'=>28],
            ['name'=>'Peumo','province_id'=>28],
            ['name'=>'Pichidegua','province_id'=>28],
            ['name'=>'Quinta de Tilcoco','province_id'=>28],
            ['name'=>'Rancagua','province_id'=>28],
            ['name'=>'Rengo','province_id'=>28],
            ['name'=>'Requínoa','province_id'=>28],
            ['name'=>'San Vicente de Tagua Tagua','province_id'=>28],
            ['name'=>'Chépica','province_id'=>29],
            ['name'=>'Chimbarongo','province_id'=>29],
            ['name'=>'Lolol','province_id'=>29],
            ['name'=>'Nancagua','province_id'=>29],
            ['name'=>'Palmilla','province_id'=>29],
            ['name'=>'Peralillo','province_id'=>29],
            ['name'=>'Placilla','province_id'=>29],
            ['name'=>'Pumanque','province_id'=>29],
            ['name'=>'San Fernando','province_id'=>29],
            ['name'=>'Santa Cruz','province_id'=>29],
            ['name'=>'La Estrella','province_id'=>30],
            ['name'=>'Litueche','province_id'=>30],
            ['name'=>'Marchigüe','province_id'=>30],
            ['name'=>'Navidad','province_id'=>30],
            ['name'=>'Paredones','province_id'=>30],
            ['name'=>'Pichilemu','province_id'=>30],
            ['name'=>'Curicó','province_id'=>31],
            ['name'=>'Hualañé','province_id'=>31],
            ['name'=>'Licantén','province_id'=>31],
            ['name'=>'Molina','province_id'=>31],
            ['name'=>'Rauco','province_id'=>31],
            ['name'=>'Romeral','province_id'=>31],
            ['name'=>'Sagrada Familia','province_id'=>31],
            ['name'=>'Teno','province_id'=>31],
            ['name'=>'Vichuquén','province_id'=>31],
            ['name'=>'Talca','province_id'=>32],
            ['name'=>'San Clemente','province_id'=>32],
            ['name'=>'Pelarco','province_id'=>32],
            ['name'=>'Pencahue','province_id'=>32],
            ['name'=>'Maule','province_id'=>32],
            ['name'=>'San Rafael','province_id'=>32],
            ['name'=>'Curepto','province_id'=>33],
            ['name'=>'Constitución','province_id'=>32],
            ['name'=>'Empedrado','province_id'=>32],
            ['name'=>'Río Claro','province_id'=>32],
            ['name'=>'Linares','province_id'=>33],
            ['name'=>'San Javier','province_id'=>33],
            ['name'=>'Parral','province_id'=>33],
            ['name'=>'Villa Alegre','province_id'=>33],
            ['name'=>'Longaví','province_id'=>33],
            ['name'=>'Colbún','province_id'=>33],
            ['name'=>'Retiro','province_id'=>33],
            ['name'=>'Yerbas Buenas','province_id'=>33],
            ['name'=>'Cauquenes','province_id'=>34],
            ['name'=>'Chanco','province_id'=>34],
            ['name'=>'Pelluhue','province_id'=>34],
            ['name'=>'Bulnes','province_id'=>35],
            ['name'=>'Chillán','province_id'=>35],
            ['name'=>'Chillán Viejo','province_id'=>35],
            ['name'=>'El Carmen','province_id'=>35],
            ['name'=>'Pemuco','province_id'=>35],
            ['name'=>'Pinto','province_id'=>35],
            ['name'=>'Quillón','province_id'=>35],
            ['name'=>'San Ignacio','province_id'=>35],
            ['name'=>'Yungay','province_id'=>35],
            ['name'=>'Cobquecura','province_id'=>36],
            ['name'=>'Coelemu','province_id'=>36],
            ['name'=>'Ninhue','province_id'=>36],
            ['name'=>'Portezuelo','province_id'=>36],
            ['name'=>'Quirihue','province_id'=>36],
            ['name'=>'Ránquil','province_id'=>36],
            ['name'=>'Treguaco','province_id'=>36],
            ['name'=>'San Carlos','province_id'=>37],
            ['name'=>'Coihueco','province_id'=>37],
            ['name'=>'San Nicolás','province_id'=>37],
            ['name'=>'Ñiquén','province_id'=>37],
            ['name'=>'San Fabián','province_id'=>37],
            ['name'=>'Alto Biobío','province_id'=>38],
            ['name'=>'Antuco','province_id'=>38],
            ['name'=>'Cabrero','province_id'=>38],
            ['name'=>'Laja','province_id'=>38],
            ['name'=>'Los Ángeles','province_id'=>38],
            ['name'=>'Mulchén','province_id'=>38],
            ['name'=>'Nacimiento','province_id'=>38],
            ['name'=>'Negrete','province_id'=>38],
            ['name'=>'Quilaco','province_id'=>38],
            ['name'=>'Quilleco','province_id'=>38],
            ['name'=>'San Rosendo','province_id'=>38],
            ['name'=>'Santa Bárbara','province_id'=>38],
            ['name'=>'Tucapel','province_id'=>38],
            ['name'=>'Yumbel','province_id'=>38],
            ['name'=>'Concepción','province_id'=>39],
            ['name'=>'Coronel','province_id'=>39],
            ['name'=>'Chiguayante','province_id'=>39],
            ['name'=>'Florida','province_id'=>39],
            ['name'=>'Hualpén','province_id'=>39],
            ['name'=>'Hualqui','province_id'=>39],
            ['name'=>'Lota','province_id'=>39],
            ['name'=>'Penco','province_id'=>39],
            ['name'=>'San Pedro de La Paz','province_id'=>39],
            ['name'=>'Santa Juana','province_id'=>39],
            ['name'=>'Talcahuano','province_id'=>39],
            ['name'=>'Tomé','province_id'=>39],
            ['name'=>'Arauco','province_id'=>40],
            ['name'=>'Cañete','province_id'=>40],
            ['name'=>'Contulmo','province_id'=>40],
            ['name'=>'Curanilahue','province_id'=>40],
            ['name'=>'Lebu','province_id'=>40],
            ['name'=>'Los Álamos','province_id'=>40],
            ['name'=>'Tirúa','province_id'=>40],
            ['name'=>'Angol','province_id'=>41],
            ['name'=>'Collipulli','province_id'=>41],
            ['name'=>'Curacautín','province_id'=>41],
            ['name'=>'Ercilla','province_id'=>41],
            ['name'=>'Lonquimay','province_id'=>41],
            ['name'=>'Los Sauces','province_id'=>41],
            ['name'=>'Lumaco','province_id'=>41],
            ['name'=>'Purén','province_id'=>41],
            ['name'=>'Renaico','province_id'=>41],
            ['name'=>'Traiguén','province_id'=>41],
            ['name'=>'Victoria','province_id'=>41],
            ['name'=>'Temuco','province_id'=>42],
            ['name'=>'Carahue','province_id'=>42],
            ['name'=>'Cholchol','province_id'=>42],
            ['name'=>'Cunco','province_id'=>42],
            ['name'=>'Curarrehue','province_id'=>42],
            ['name'=>'Freire','province_id'=>42],
            ['name'=>'Galvarino','province_id'=>42],
            ['name'=>'Gorbea','province_id'=>42],
            ['name'=>'Lautaro','province_id'=>42],
            ['name'=>'Loncoche','province_id'=>42],
            ['name'=>'Melipeuco','province_id'=>42],
            ['name'=>'Nueva Imperial','province_id'=>42],
            ['name'=>'Padre Las Casas','province_id'=>42],
            ['name'=>'Perquenco','province_id'=>42],
            ['name'=>'Pitrufquén','province_id'=>42],
            ['name'=>'Pucón','province_id'=>42],
            ['name'=>'Saavedra','province_id'=>42],
            ['name'=>'Teodoro Schmidt','province_id'=>42],
            ['name'=>'Toltén','province_id'=>42],
            ['name'=>'Vilcún','province_id'=>42],
            ['name'=>'Villarrica','province_id'=>42],
            ['name'=>'Valdivia','province_id'=>43],
            ['name'=>'Corral','province_id'=>43],
            ['name'=>'Lanco','province_id'=>43],
            ['name'=>'Los Lagos','province_id'=>43],
            ['name'=>'Máfil','province_id'=>43],
            ['name'=>'Mariquina','province_id'=>43],
            ['name'=>'Paillaco','province_id'=>43],
            ['name'=>'Panguipulli','province_id'=>43],
            ['name'=>'La Unión','province_id'=>44],
            ['name'=>'Futrono','province_id'=>44],
            ['name'=>'Lago Ranco','province_id'=>44],
            ['name'=>'Río Bueno','province_id'=>44],
            ['name'=>'Osorno','province_id'=>45],
            ['name'=>'Puerto Octay','province_id'=>45],
            ['name'=>'Purranque','province_id'=>45],
            ['name'=>'Puyehue','province_id'=>45],
            ['name'=>'Río Negro','province_id'=>45],
            ['name'=>'San Juan de la Costa','province_id'=>45],
            ['name'=>'San Pablo','province_id'=>45],
            ['name'=>'Calbuco','province_id'=>46],
            ['name'=>'Cochamó','province_id'=>46],
            ['name'=>'Fresia','province_id'=>46],
            ['name'=>'Frutillar','province_id'=>46],
            ['name'=>'Llanquihue','province_id'=>46],
            ['name'=>'Los Muermos','province_id'=>46],
            ['name'=>'Maullín','province_id'=>46],
            ['name'=>'Puerto Montt','province_id'=>46],
            ['name'=>'Puerto Varas','province_id'=>46],
            ['name'=>'Ancud','province_id'=>47],
            ['name'=>'Castro','province_id'=>47],
            ['name'=>'Chonchi','province_id'=>47],
            ['name'=>'Curaco de Vélez','province_id'=>47],
            ['name'=>'Dalcahue','province_id'=>47],
            ['name'=>'Puqueldón','province_id'=>47],
            ['name'=>'Queilén','province_id'=>47],
            ['name'=>'Quellón','province_id'=>47],
            ['name'=>'Quemchi','province_id'=>47],
            ['name'=>'Quinchao','province_id'=>47],
            ['name'=>'Chaitén','province_id'=>48],
            ['name'=>'Futaleufú','province_id'=>48],
            ['name'=>'Hualaihué','province_id'=>48],
            ['name'=>'Palena','province_id'=>48],
            ['name'=>'Lago Verde','province_id'=>49],
            ['name'=>'Coihaique','province_id'=>49],
            ['name'=>'Aysén','province_id'=>50],
            ['name'=>'Cisnes','province_id'=>50],
            ['name'=>'Guaitecas','province_id'=>50],
            ['name'=>'Río Ibáñez','province_id'=>51],
            ['name'=>'Chile Chico','province_id'=>51],
            ['name'=>'Cochrane','province_id'=>52],
            ['name'=>'O\'Higgins','province_id'=>52],
            ['name'=>'Tortel','province_id'=>52],
            ['name'=>'Natales','province_id'=>53],
            ['name'=>'Torres del Paine','province_id'=>53],
            ['name'=>'Laguna Blanca','province_id'=>54],
            ['name'=>'Punta Arenas','province_id'=>54],
            ['name'=>'Río Verde','province_id'=>54],
            ['name'=>'San Gregorio','province_id'=>54],
            ['name'=>'Porvenir','province_id'=>55],
            ['name'=>'Primavera','province_id'=>55],
            ['name'=>'Timaukel','province_id'=>55],
            ['name'=>'Cabo de Hornos','province_id'=>56],
            ['name'=>'Antártica','province_id'=>56]
        ]);
    }
}
